name: Mirror to GitLab

on:
  push:
    branches:
      - '*' # Trigger on updates to all branches
  delete:
    branches:
      - '*' # Trigger on deletions of all branches

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source repository
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history
          fetch-tags: true # Fetch all tags

      # Step 2: Switch to a detached HEAD
      - name: Switch to Detached HEAD
        run: git checkout --detach

      # Step 3: Fetch all branches
      - name: Fetch All Branches
        run: |
          git config remote.origin.fetch "+refs/heads/*:refs/heads/*"
          git fetch --all

      # Step 4: Add GitLab as a remote
      - name: Add GitLab Remote
        run: git remote add gitlab https://brunclik:${{ secrets.GITLAB_TOKEN }}@gitlab.rtsoft.cz/co-hackaton-rtsoft-2024/co-hackaton-2024-project-5.git

      # Step 5: Push all branches and tags to GitLab
      - name: Push to GitLab
        run: |
          git push gitlab --all # Push all branches
          git push gitlab --tags # Push all tags
